---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/synchronous-steve/concourse.git
      branch: master

jobs:
  - name: job-pass-files
    public: true
    plan:
      - get: resource-tutorial
      - task: create-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
          outputs:
            - name: some-files

          run:
            path: resource-tutorial/create_some_files.sh

      - task: show-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang, tag: 1.9-alpine}

          inputs:
            - name: resource-tutorial
            - name: some-files

          run:
            path: resource-tutorial/show_files.sh
